[build]
HUGO_VERSION = "0.80.0"
publish = "html"
command = "git submodule update -f --init && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.80.0"

[context.branch-deploy.environment]
HUGO_VERSION = "0.80.0"
